baseURL: https://www.fragmentis-vitae.org/ # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: "Fragments #KH50"
paginate: 5
theme: charlolamode

menu:
  main:
    - name: Pr√©sentation
      url: /presentation/
      weight: 10
    - name: Porteurs du projet
      url: /porteurs-projet/
      weight: 20
    - name: Soutiens
      url: /soutiens/
      weight: 30
    - name: Contact
      url: /contact/
      weight: 40

# - name: Contact
#   url: /contact/
#   weight: 30
# - name: Articles
#   url: /articles/
#   weight: 20
# - name: Projects
#   url: /projects/
#   weight: 15

# - name: Categories
#   url: /categories/
#   weight: 10
# - name: new Tab
#   url: /newtab/
#   weight: defines order of tabs

params:
  author: loiklak
  description: "Le projet FRAGMENTS #KH50 vise √† r√©unir les fragments de l‚Äôhistoire du peuple khmer, exil√© de la guerre et du g√©nocide au Cambodge, √† l‚Äôoccasion du cinquantenaire de la prise de Phnom Penh en 2025."

  defaultTheme: auto
  # disableThemeToggle: true
  displayFullLangName: true
  ShowCodeCopyButtons: true
  logoUrl: "/images/fragment-rond.svg"

  profileMode:
    # Disable to populate home page with 'mainSections' content
    enabled: true
    title: Fragments#KH50
    description:
      "Fragments #KH50 a √©t√© principalement initi√© par des descendants de Cambodgiens.\n

      Du fait de l‚Äôexil et de la guerre, chacun ne poss√®de que quelques fragments de l‚Äôhistoire de sa famille.\n

      **Le projet #FRAGMENTS KH50 veut rassembler ces fragments d‚Äôhistoires personnelles pour reconstituer la M√©moire collective**\n

      [> _En savoir plus_](/presentation/)"

    imageUrl: "/images/fragment-rond.svg"
    imageTitle: logo fragments
    imageWidth: 300
    imageHeight: 300
    buttons:
      - name: Adh√©rer √† l'association ü§ù
        url: https://www.helloasso.com/associations/fragmentis-vitae/adhesions/adhesion
      - name: Faire un don ‚ù§Ô∏è
        url: https://www.helloasso.com/associations/fragmentis-vitae/formulaires/1

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/showcase/fragments-kh50/"
    - name: twitter
      url: "https://twitter.com/FragmentisVitae"
    - name: facebook
      url: "https://www.facebook.com/Fragments.kh50"
    - name: instagram
      url: "https://www.instagram.com/fragmentis.v/?igshid=YmMyMTA2M2Y"

  # change favicon in images folder (icon for web tab)
  assets:
    favicon: "/images/favicon.ico"
    favicon16x16: "/images/favicon-16x16.png"
    favicon32x32: "/images/favicon-32x32.png"
    apple_touch_icon: "/images/apple-touch-icon.png"
    safari_pinned_tab: "/images/apple-touch-icon.png"

copyright: ¬© 2023 FragmentisVitaeAsia

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

markup:
  goldmark:
    renderer:
      unsafe: true
