baseURL: https://www.fragmentis-vitae.org/ # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: "Fragments #KH50"
paginate: 5
theme: charlolamode

menu:
  main:
    - name: Pr√©sentation
      url: /presentation/
      weight: 10
    - name: Events / Actus
      url: /events-actus/
      weight: 13
    - name: T√©moigner
      url: /temoignages/
      weight: 15
    - name: Qui porte le projet ? 
      url: /porteurs-projet/
      weight: 20
    - name: Soutiens
      url: /soutiens/
      weight: 30
    - name: Contact
      url: /contact/
      weight: 40
    - name: Presse
      url: /espace-presse/
      weight: 50

# - name: Contact
#   url: /contact/
#   weight: 30
# - name: Articles
#   url: /articles/
#   weight: 20
# - name: Projects
#   url: /projects/
#   weight: 15

# - name: Categories
#   url: /categories/
#   weight: 10
# - name: new Tab
#   url: /newtab/
#   weight: defines order of tabs

params:
  author: loiklak
  description: "Le projet Fragments #KH50 est principalement initi√© par des descendants de r√©fugi√©s ayant fui le Cambodge et port√© par l‚Äôassociation Loi 1901, Fragmentis Vitae Asia. 

Du fait de l‚Äôexil, de la guerre civile et de la p√©riode g√©nocidaire, chacun ne poss√®de que quelques fragments de l‚Äôhistoire de sa famille.

FRAGMENTS #KH50 a pour objectif de rassembler ces fragments d‚Äôhistoires pour reconstituer la M√©moire collective."


  defaultTheme: auto
  # disableThemeToggle: true
  displayFullLangName: true
  ShowCodeCopyButtons: true
  logoUrl: "/images/fragment-rond.svg"

  profileMode:
    # Disable to populate home page with 'mainSections' content
    enabled: true
    title: "Fragments #KH50"
    description:
      "Le projet Fragments #KH50 est principalement initi√© par des descendants de r√©fugi√©s ayant fui le Cambodge et port√© par l‚Äôassociation Loi 1901, Fragmentis Vitae Asia. 
Du fait de l‚Äôexil, de la guerre civile et de la p√©riode g√©nocidaire, chacun ne poss√®de que quelques fragments de l‚Äôhistoire de sa famille.\n



      **FRAGMENTS #KH50 a pour objectif de rassembler ces fragments d‚Äôhistoires pour reconstituer la M√©moire collective.**\n
      "

    imageUrl: "/images/fragment-rond.svg"
    imageTitle: logo fragments
    imageWidth: 300
    imageHeight: 300
    buttons:
      - name: Adh√©rer √† l'association ü§ù
        url: https://www.helloasso.com/associations/fragmentis-vitae/adhesions/adhesion
      - name: Faire un don ‚ù§Ô∏è
        url: https://www.helloasso.com/associations/fragmentis-vitae/formulaires/1
      - name: T√©moigner üó£Ô∏è
        url: /temoignages/

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/showcase/fragments-kh50/"
    - name: twitter
      url: "https://twitter.com/FragmentisVitae"
    - name: facebook
      url: "https://www.facebook.com/Fragments.kh50"
    - name: instagram
      url: "https://www.instagram.com/fragmentis.v/?igshid=YmMyMTA2M2Y"

  # change favicon in images folder (icon for web tab)
  assets:
    favicon: "/images/favicon.ico"
    favicon16x16: "/images/favicon-16x16.png"
    favicon32x32: "/images/favicon-32x32.png"
    apple_touch_icon: "/images/apple-touch-icon.png"
    safari_pinned_tab: "/images/apple-touch-icon.png"

copyright: ¬© 2023 FragmentisVitaeAsia

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

markup:
  goldmark:
    renderer:
      unsafe: true
